/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
  IsDate,
} from "class-validator";

import { ExchangeRateWhereUniqueInput } from "../../exchangeRate/base/ExchangeRateWhereUniqueInput";
import { Type } from "class-transformer";
import { LedgerEntryUpdateManyWithoutTransactionsInput } from "./LedgerEntryUpdateManyWithoutTransactionsInput";
import { WalletWhereUniqueInput } from "../../wallet/base/WalletWhereUniqueInput";

@InputType()
class TransactionUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  amount?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  currency?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExchangeRateWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExchangeRateWhereUniqueInput)
  @IsOptional()
  @Field(() => ExchangeRateWhereUniqueInput, {
    nullable: true,
  })
  exchangeRate?: ExchangeRateWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LedgerEntryUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => LedgerEntryUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => LedgerEntryUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  ledgerEntries?: LedgerEntryUpdateManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  timestamp?: Date | null;

  @ApiProperty({
    required: false,
    type: () => WalletWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WalletWhereUniqueInput)
  @IsOptional()
  @Field(() => WalletWhereUniqueInput, {
    nullable: true,
  })
  wallet?: WalletWhereUniqueInput | null;
}

export { TransactionUpdateInput as TransactionUpdateInput };
