/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExchangeRateService } from "../exchangeRate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExchangeRateCreateInput } from "./ExchangeRateCreateInput";
import { ExchangeRate } from "./ExchangeRate";
import { ExchangeRateFindManyArgs } from "./ExchangeRateFindManyArgs";
import { ExchangeRateWhereUniqueInput } from "./ExchangeRateWhereUniqueInput";
import { ExchangeRateUpdateInput } from "./ExchangeRateUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExchangeRateControllerBase {
  constructor(
    protected readonly service: ExchangeRateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExchangeRate })
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExchangeRate(
    @common.Body() data: ExchangeRateCreateInput
  ): Promise<ExchangeRate> {
    return await this.service.createExchangeRate({
      data: data,
      select: {
        createdAt: true,
        currencyFrom: true,
        currencyTo: true,
        id: true,
        rate: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExchangeRate] })
  @ApiNestedQuery(ExchangeRateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exchangeRates(@common.Req() request: Request): Promise<ExchangeRate[]> {
    const args = plainToClass(ExchangeRateFindManyArgs, request.query);
    return this.service.exchangeRates({
      ...args,
      select: {
        createdAt: true,
        currencyFrom: true,
        currencyTo: true,
        id: true,
        rate: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput
  ): Promise<ExchangeRate | null> {
    const result = await this.service.exchangeRate({
      where: params,
      select: {
        createdAt: true,
        currencyFrom: true,
        currencyTo: true,
        id: true,
        rate: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput,
    @common.Body() data: ExchangeRateUpdateInput
  ): Promise<ExchangeRate | null> {
    try {
      return await this.service.updateExchangeRate({
        where: params,
        data: data,
        select: {
          createdAt: true,
          currencyFrom: true,
          currencyTo: true,
          id: true,
          rate: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExchangeRate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExchangeRate(
    @common.Param() params: ExchangeRateWhereUniqueInput
  ): Promise<ExchangeRate | null> {
    try {
      return await this.service.deleteExchangeRate({
        where: params,
        select: {
          createdAt: true,
          currencyFrom: true,
          currencyTo: true,
          id: true,
          rate: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Transaction",
    action: "read",
    possession: "any",
  })
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: ExchangeRateWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        currency: true,

        exchangeRate: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        timestamp: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "update",
    possession: "any",
  })
  async connectTransactions(
    @common.Param() params: ExchangeRateWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateExchangeRate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "update",
    possession: "any",
  })
  async updateTransactions(
    @common.Param() params: ExchangeRateWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateExchangeRate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "ExchangeRate",
    action: "update",
    possession: "any",
  })
  async disconnectTransactions(
    @common.Param() params: ExchangeRateWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateExchangeRate({
      where: params,
      data,
      select: { id: true },
    });
  }
}
